# Generated by Django 4.2.5 on 2023-09-14 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogAuthor",
            new_name="Author",
        ),
        migrations.RenameModel(
            old_name="BlogComment",
            new_name="Comment",
        ),
    ]
