# Generated by Django 4.2.5 on 2023-09-14 20:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_rename_blogauthor_author_rename_blogcomment_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="BlogAuthor",
        ),
        migrations.RenameModel(
            old_name="Comment",
            new_name="BlogComment",
        ),
    ]
