# Generated by Django 4.2.5 on 2023-10-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_author_blogauthor_rename_comment_blogcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
